### ISSUE TITLE
Add the entire chainlog as public variables on mcd instance

### ISSUE THREAD

**Issue by hexonaut** [makerdao/dss-test#5]
Should add all contracts as variables for convenience.

**Comment by gbalabasquer** [comment]
Hmmm how would that work?

**Comment by hexonaut** [comment]
Just like this: https://github.com/makerdao/dss-test/blob/master/src/MCD.sol#L27

It's just we are missing some things like end, vest, etc.

**Comment by hexonaut** [comment]
Done https://github.com/makerdao/dss-test/pull/8
